name: Test Pitchfork Parser

on:
  workflow_dispatch:  # Позволяет запускать вручную из вкладки Actions

jobs:
  run-pitchfork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 feedgen

      - name: Run Pitchfork parser
        working-directory: backend
        run: |
          python pitchfork.py
